# Generated by Django 3.0.3 on 2020-04-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
