# Generated by Django 3.0.3 on 2020-04-11 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 9, 10, 32, 748947, tzinfo=utc)),
        ),
    ]
