# Generated by Django 3.0.3 on 2020-04-11 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200411_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 9, 28, 13, 898467, tzinfo=utc)),
        ),
    ]
